# Generated by Django 5.2.6 on 2025-09-12 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_product_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nama',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
